module.exports = {
  btc: {
    id: 'bitcoin',
    name: 'Bitcoin',
    color: '#f7931a',
    about: "Le Bitcoin est la première et la plus connue des cryptomonnaies. Il fonctionne sur un réseau décentralisé et sécurisé.",
    link: 'bitcoin.org',
  },
  eth: {
    id: 'ethereum',
    name: 'Ethereum',
    color: '#8a92b2',
    about: "Ethereum est une plateforme décentralisée qui exécute des contrats intelligents (smart contracts).",
    link: 'ethereum.org',
  },
  sol: {
    id: 'solana',
    name: 'Solana',
    color: '#66f9a1',
    about: "Solana est une blockchain à haut débit, conçue pour des transactions rapides et peu coûteuses.",
    link: 'solana.com',
  },
  bnb: {
    id: 'binancecoin',
    name: 'BNB',
    color: '#f3ba2f',
    about: "BNB est le jeton natif de l'écosystème Binance, utilisé pour les frais et de nombreuses applications.",
    link: 'bnbchain.org',
  },
  doge: {
    id: 'dogecoin',
    name: 'Dogecoin',
    color: '#c2a633',
    about: "Dogecoin, né d'un mème, est devenue l'une des cryptomonnaies les plus suivies par sa communauté.",
    link: 'dogecoin.com',
  },
  xrp: {
    id: 'ripple',
    name: 'XRP',
    color: '#25a9e0',
    about: "XRP est conçu pour faciliter les paiements transfrontaliers rapides entre institutions financières.",
    link: 'ripple.com',
  },
  usdt: {
    id: 'tether',
    name: 'Tether',
    color: '#26a17b',
    about: "Tether (USDT) est un stablecoin indexé sur le dollar américain, utilisé comme valeur refuge sur les marchés crypto.",
    link: 'tether.to',
  },
  ton: {
    id: 'the-open-network',
    name: 'Toncoin',
    color: '#0088cc',
    about: "Toncoin alimente The Open Network, une blockchain conçue à l'origine par l'équipe de Telegram.",
    link: 'ton.org',
  },
}
